### ISSUE TITLE
Fix Linting in src.DigitalDriveShaft.analysis

### ISSUE THREAD

**Issue by willi-z** [Modular-Design/DigitalDriveShaft#6]
**Describe the bug**
in ``src.DigitalDriveShaft.analysis`` are several files that seems to no use and cause ``flake`` cause trouble.
the files in particular are:
- ``freier_Bereich.py``
-  ``freier_Bereich_v01.py``
- ``test.py``
- ``Wellenauslegung.py``
- ``Wellenauslegung_v01.py``

**Expected behavior**
Clear or remove files. Use some of the information as tests.

**Comment by Alrik-ILK** [comment]
files removed. Some of the information used as tests.
